# Generated by Django 5.2.8 on 2025-11-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birth_data',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='oder',
            new_name='order',
        ),
    ]
